name: futrah
description: A new Flutter project.
version: 1.0.0+4
environment:
#  sdk: '>=2.19.4 <3.0.0'
  sdk: '>=3.0.5 <4.0.0'

publish_to: 'none'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  flutter_localization: ^0.1.10
  get_it: ^7.6.0
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.1
  flutter_bloc: ^8.1.2
  pin_code_fields: ^7.4.0
  flutter_conditional_rendering: ^2.0.0
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  url_launcher: ^6.1.11
  image_picker: ^0.8.7+5
  bluetooth_print: ^4.3.0
  intl:
  flutter_paytabs_bridge: ^2.3.5
  fluttertoast: ^8.2.1
  sunmi_printer_plus: ^2.1.1
#  sunmi_printer_service:
  device_info: ^2.0.3
  country_code_picker: ^3.0.0
#  permission_handler: ^10.2.0
  logger: ^1.3.0
  blue_print_pos: ^0.0.14
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lang/
    - assets/images/cache.png
    - assets/images/label_fatwra.png
    - assets/images/company.png
    - assets/images/copy.png
    - assets/images/logo.png
    - assets/images/logoEn.png
    - assets/images/mada.png
    - assets/images/product.png
    - assets/images/quickInvoice.png
    - assets/images/visa.png
    - assets/lang/ar.json
    - assets/lang/en.json
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Arabic_B.ttf
        - asset: assets/fonts/Ubuntu-Arabic_R.ttf
