// import 'package:flutter/material.dart';
// import 'package:flutter_bloc/flutter_bloc.dart';
// import 'package:futrah/controller/constants/components.dart';
// import 'package:futrah/controller/constants/size.dart';
// import 'package:futrah/controller/resources/localizations/app_localizations.dart';
// import 'package:futrah/controller/routes/app_router_imports.dart';
// import 'package:futrah/controller/services/helpers/error_msg.dart';
// import 'package:futrah/view/screens/auth/cubit/login_cubit.dart';
// import 'package:futrah/view/screens/auth/cubit/login_state.dart';
// import 'package:futrah/view/screens/auth/view/widgets/auth_logo.dart';
// import 'package:futrah/view/screens/auth/view/widgets/login_btn.dart';
// import 'package:futrah/view/screens/auth/view/widgets/login_filed.dart';
// import 'package:futrah/view/screens/auth/view/widgets/login_terms.dart';
// import 'package:futrah/view/widgets/change_lang_btn.dart';
// import 'package:futrah/view/widgets/custom_app_bar.dart';
// import 'package:futrah/view/widgets/custom_condition.dart';
// import 'package:futrah/view/widgets/custom_loading.dart';
//
// part 'phone_screen.dart';
