// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPxx5ZvpiQ0v4F_V-6aj1AkcrEBAc4l7Q',
    appId: '1:195925313064:android:23cf2b1d9c0ba6dc9d171d',
    messagingSenderId: '195925313064',
    projectId: 'futara-a63de',
    storageBucket: 'futara-a63de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1EqLshYu2K_VZ2T6ApOC6BZhTQ0tBklo',
    appId: '1:195925313064:ios:77af153e0dde6c7e9d171d',
    messagingSenderId: '195925313064',
    projectId: 'futara-a63de',
    storageBucket: 'futara-a63de.appspot.com',
    androidClientId: '195925313064-9gisg7b8i02h3osfldens3adnu92qbth.apps.googleusercontent.com',
    iosClientId: '195925313064-njlqj0f27sqc8sk7vic17b8vgi0lg4i2.apps.googleusercontent.com',
    iosBundleId: 'com.metafortech.futara',
  );
}
