import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:futrah/controller/constants/components.dart';
import 'package:futrah/controller/constants/size.dart';
import 'package:futrah/controller/resources/localizations/app_localizations.dart';
import 'package:futrah/controller/resources/theme/colors_manager.dart';
import 'package:futrah/controller/routes/app_router_imports.dart';
import 'package:futrah/view/screens/add_customers/cubit/customers_cubit.dart';
import 'package:futrah/view/screens/add_customers/cubit/customers_state.dart';
import 'package:futrah/view/screens/add_customers/view/widgets/customers_list.dart';
import 'package:futrah/view/screens/add_customers/view/widgets/text_fileds_part.dart';
import 'package:futrah/view/screens/auth/view/widgets/login_btn.dart';
import 'package:futrah/view/widgets/cancel_button.dart';
import 'package:futrah/view/widgets/custom_app_bar.dart';
import 'package:futrah/view/widgets/custom_condition.dart';
import 'package:futrah/view/widgets/custom_loading.dart';
import 'package:futrah/view/widgets/my_text.dart';

part 'customers_view.dart';
